theme: minima
title: GitHub Page Test
author: Csaba Magyar
email: magyar.csaba.mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
... some text here ...

# social links
github_username:  MagyarCsaba # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
