title: GitHub Page Test
author: Csaba Magyar
email: magyar.csaba.mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here comes the description for my GitHub Test Page / new site. This is edited in _config.yml file.
  It will appear in the document head meta (for
  Google search results) and in my feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
